---
downloads: ~/.ansible-downloads/
mount_path: /Volumes

# set to yes to run certain tasks
configure_aws: yes
configure_dotfiles: no
configure_sudoers: no
configure_terminal: yes
configure_osx: no
configure_vim: yes
configure_vscode: yes

dotfiles_repo: "git@github.com:chrisminton/dotfiles.git"
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/Development/GitHub/dotfiles
dotfiles_files:
  - .gitignore
  - .config/powerline
  - .osx
  - .vimrc
  - .zshrc

homebrew_installed_packages:
  - autoconf
  - awscli
  - bash
  - bash-completion
  - bosh-cli # cloud foundry cli tools
  - cf-cli   # cloud foundry cli tools
  - coreutils
  - cowsay
  - direnv
  - git
  - git-crypt
  - git-duet
  - gnu-tar
  - go
  - gpg
  - hub
  - httpie
  - iperf
  - jq
  - kubernetes-cli
  - kubernetes-helm
  - libevent
  - mcrypt
  - nmap
  - node
  - nvm
  - openssl
  - packer
  - pinentry-mac # for GPG signing git commits
  - python3
  - readline
  - reattach-to-user-namespace
  - remind101/formulae/assume-role
  - sqlite
  - ssh-copy-id
  - terraform
  - terraform_landscape
  - tmux
  - wget
  - wireshark
  - vault
  - vim
  - yq

homebrew_taps:
  - homebrew/core
  - caskroom/cask
  - cloudfoundry/tap
  - git-duet/tap

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - docker
  - firefox
  - google-chrome
  - gpg-suite
  - gpgtools
  - handbrake
  - iterm2
  - keybase
  - macpass # KeyPass Mac port
  - microsoft-teams
  - slack
  - spectacle
  - vagrant
  - virtualbox
  - visual-studio-code

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
  # - name: drush
  #   state: present # present/absent, default: present
  #   version: "^8.1" # default: N/A
gem_packages: []
  # - name: bundler
  #   state: present # present/absent/latest, default: present
  #   version: "~> 1.15.1" # default: N/A
npm_packages: []
  # - name: webpack
  #   state: present # present/absent/latest, default: present
  #   version: "^2.6" # default: N/A
pip_packages:
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A
  - name: aws-shell
  - name: boto3
  - name: netifaces # for powerline status internal IP
  - name: powerline-status
  - name: pylint

# Chef
chefdk_version: 2.5.3

# vim setup
vim_plugin_dir: ~/.vim/autoload

# vscode setup
vscode_util: /usr/local/bin/code
vscode_extensions:
  - bibhasdn.unique-lines
  - davidanson.vscode-markdownlint
  - eriklynd.json-tools
  - jmmeessen.jenkins-declarative-support
  - mauve.terraform
  - ms-kubernetes-tools.vscode-kubernetes-tools
  - ms-python.python
  - pendrica.chef
  - PeterJausovec.vscode-docker
  - rebornix.ruby
  - redhat.vscode-yaml
  - timonwong.shellcheck

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
