---
downloads: ~/.ansible-downloads/

configure_dotfiles: yes
configure_sudoers: no
configure_terminal: yes
configure_osx: yes
configure_vim: yes
configure_vscode: yes

dotfiles_repo: "git@github.com:chrisminton/dotfiles.git"
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/Development/GitHub/dotfiles
dotfiles_files:
  - .gitignore
  - .osx
  - .vimrc
  - .zshrc


homebrew_installed_packages:
  - autoconf
  - awscli
  - bash
  - bash-completion
  - coreutils
  - cowsay
  - direnv
  - git
  - git-crypt
  - git-duet
  - gnu-tar
  - go
  - gpg
  - hub
  - httpie
  - iperf
  - jq
  - kubernetes-cli
  - kubernetes-helm
  - libevent
  - mcrypt
  - nmap
  - node
  - nvm
  - openssl
  - packer
  - python3
  - readline
  - reattach-to-user-namespace
  - remind101/formulae/assume-role
  - sqlite
  - ssh-copy-id
  - terraform
  - terraform_landscape
  - tmux
  - wget
  - wireshark
  - vault
  - vim
  - yq

homebrew_taps:
  - homebrew/core
  - caskroom/cask
  - git-duet/tap

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - firefox
  - google-chrome
  - handbrake
  - iterm2
  - slack
  - spectacle
  - vagrant
  - virtualbox
  - visual-studio-code

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
  # - name: drush
  #   state: present # present/absent, default: present
  #   version: "^8.1" # default: N/A
gem_packages: []
  # - name: bundler
  #   state: present # present/absent/latest, default: present
  #   version: "~> 1.15.1" # default: N/A
npm_packages: []
  # - name: webpack
  #   state: present # present/absent/latest, default: present
  #   version: "^2.6" # default: N/A
pip_packages:
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A
  - name: powerline-status

# vim setup
vim_plugin_dir: ~/.vim/autoload

# vscode setup
vscode_util: /usr/local/bin/code
vscode_extensions:
  - mauve.terraform
  - ms-kubernetes-tools.vscode-kubernetes-tools
  - ms-python.python
  - PeterJausovec.vscode-docker
  - rebornix.ruby
  - redhat.vscode-yaml

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
