---
# Create example AWS config files unless they already exist
- name: Create AWS CLI directory
  file:
    path: ~/.aws
    state: directory

- name: Create file from template if it doesn't exist already.
  copy:
    src: "files/aws/{{ item }}"
    dest: "~/.aws/{{ item }}"
    force: no
  with_items:
    - config
    - credentials
