---
- name: assert binding of oh-my-zsh
  command: test -d ~/.oh-my-zsh
  ignore_errors: True
  register: omz_bound

- name: Download oh-my-zsh
  git: repo=git://github.com/robbyrussell/oh-my-zsh.git
       dest=~/.oh-my-zsh accept_hostkey=true
  when: omz_bound is failed

- name: Install zsh-users plugins
  git: repo=git://github.com/zsh-users/{{ item }}.git
       dest=~/.oh-my-zsh/custom/plugins/{{ item }}
       accept_hostkey=true
  when: omz_bound is failed
  with_items:
    - zsh-completions
    - zsh-syntax-highlighting

- name: change shell
  command: chsh -s /bin/zsh
  when: omz_bound is failed  